# Generated by Django 6.0.2 on 2026-04-22 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_alter_contract_status_alter_contractevent_event_type'),
        ('disputes', '0004_alter_dispute_resolved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='contracts.contract'),
        ),
    ]
