# Generated by Django 6.0.2 on 2026-04-21 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disputes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='opened_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to=settings.AUTH_USER_MODEL),
        ),
    ]
