# Generated by Django 6.0.2 on 2026-04-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0003_dispute_client_amount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='resolved_at',
            field=models.DateTimeField(),
        ),
    ]
