# Generated by Django 6.0.2 on 2026-04-23 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_alter_contractevent_event_type'),
        ('disputes', '0006_alter_dispute_resolved_at_disputerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disputerequest',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_request', to='contracts.contract'),
        ),
    ]
