# Generated by Django 6.0.2 on 2026-05-01 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_contract_created_at_contract_dispute_requested_and_more'),
        ('disputes', '0007_alter_disputerequest_contract'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='disputerequest',
            name='dispute',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='disputes.dispute'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='contracts.contract'),
        ),
        migrations.AlterField(
            model_name='disputerequest',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_request', to='contracts.contract'),
        ),
        migrations.AddIndex(
            model_name='disputerequest',
            index=models.Index(fields=['contract', 'status'], name='disputes_di_contrac_debfb1_idx'),
        ),
        migrations.AddConstraint(
            model_name='disputerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('contract',), name='one_pending_request_per_contract'),
        ),
    ]
