# Generated by Django 6.0.2 on 2026-04-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FUNDED', 'Funded'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled'), ('DISPUTED', 'Disputed')], db_index=True, default='DRAFT', max_length=20)),
                ('max_revisions', models.PositiveIntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='ContractEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('contract_created', 'Contract Created'), ('contract_cancelled', 'Contract Cancelled'), ('contract_funded', 'Contract Funded'), ('contract_activated', 'Contract Activated'), ('work_submitted', 'Work Submitted'), ('work_rejected', 'Work Rejected'), ('work_approved', 'Work Approved'), ('escrow_released', 'Escrow Released'), ('escrow_refunded', 'Escrow Refunded'), ('dispute_opened', 'Dispute Opened'), ('dispute_resolved', 'Dispute Resolved'), ('dispute_closed', 'Dispute Closed')], max_length=50)),
                ('operation_key', models.CharField(max_length=250, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('PROCESSING', 'processing'), ('PROCESSED', 'processed'), ('FAILED', 'failed')], default='PENDING', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
