# Generated by Django 6.0.2 on 2026-04-20 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('submissions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='current_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='submissions.submission'),
        ),
    ]
