# Generated by Django 6.0.2 on 2026-04-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract_current_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='max_revisions',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
