# Generated by Django 6.0.2 on 2026-03-06 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_alter_contract_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractevent',
            name='event_type',
            field=models.CharField(choices=[('activated', 'Activated'), ('work_submitted', 'Work Submitted'), ('work_approved', 'Work Approved'), ('work_rejected', 'Work Rejected'), ('cancelled', 'Cancelled')], max_length=50),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='contracts.contract')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['contract'], name='contracts_s_contrac_16911f_idx')],
            },
        ),
    ]
