# Generated by Django 6.0.2 on 2026-04-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_alter_contract_status_alter_contractevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractevent',
            name='event_type',
            field=models.CharField(choices=[('contract_created', 'Contract Created'), ('contract_cancelled', 'Contract Cancelled'), ('contract_funded', 'Contract Funded'), ('contract_activated', 'Contract Activated'), ('work_submitted', 'Work Submitted'), ('work_rejected', 'Work Rejected'), ('work_approved', 'Work Approved'), ('escrow_released', 'Escrow Released'), ('escrow_refunded', 'Escrow Refunded'), ('escrow_split', 'Escrow Split'), ('dispute_requested', 'Dispute Requested'), ('dispute_request_approved', 'Dispute Request Approved'), ('dispute_request_rejected', 'Dispute Request Rejected'), ('dispute_opened', 'Dispute Opened'), ('dispute_resolved', 'Dispute Resolved'), ('dispute_closed', 'Dispute Closed')], max_length=50),
        ),
    ]
