# Generated by Django 6.0.2 on 2026-05-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_alter_contractevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='dispute_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FUNDED', 'Funded'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded'), ('SPLIT_PAY', 'Split Pay'), ('DISPUTE_REQUESTED', 'Dispute Requested'), ('DISPUTED', 'Disputed')], db_index=True, default='DRAFT', max_length=20),
        ),
    ]
