# Generated by Django 6.0.2 on 2026-03-11 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_alter_contractevent_event_type'),
        ('jobs', '0005_alter_jobevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
    ]
