# Generated by Django 6.0.2 on 2026-03-11 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_alter_contract_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='submission',
            name='contracts_s_contrac_16911f_idx',
        ),
        migrations.AddField(
            model_name='submission',
            name='file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='submission',
            name='revision_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('FUNDED', 'Funded'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='contractevent',
            name='event_type',
            field=models.CharField(choices=[('contract_created', 'Contract Created'), ('contract_cancelled', 'Contract Cancelled'), ('contract_funded', 'Contract Funded'), ('contract_activated', 'Contract Activated'), ('work_submitted', 'Work Submitted'), ('work_rejected', 'Work Rejected'), ('work_approved', 'Work Approved'), ('escrow_released', 'Escrow Released'), ('escrow_refunded', 'Escrow Refunded')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['contract', 'revision_number'], name='contracts_s_contrac_e6b718_idx'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('contract', 'revision_number'), name='unique_revision_per_contract'),
        ),
    ]
