# Generated by Django 6.0.2 on 2026-03-11 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_alter_submission_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='current_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contracts.submission'),
        ),
    ]
