# Generated by Django 6.0.2 on 2026-03-16 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_contract_current_submission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('FUNDED', 'Funded'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled'), ('DISPUTED', 'Disputed')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=15)),
                ('resolution', models.CharField(blank=True, choices=[('CLIENT', 'Client'), ('FREELANCER', 'Freelancer'), ('SPLIT', 'Split')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='contracts.contract')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
