# Generated by Django 6.0.2 on 2026-03-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_alter_contractevent_operation_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractevent',
            name='operation_key',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
