#### AUTHENTICATION

POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username" : "admin",
    "password" : "admin"
}

###
POST http://localhost:8000/api/auth/login/ HTTP/1.1
Content-Type: application/json

{
    "username" : "freelancer",
    "password" : "freelancer"
}

###
POST http://localhost:8000/api/auth/register/ HTTP/1.1
Content-Type: application/json

{
    "username" : "test",
    "email" : "test@gmail.com",
    "password" : "test",
    "password2" : "test"
}

###
POST http://localhost:8000/api/auth/logout/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc3ODc5MzQwLCJpYXQiOjE3Nzc4NzU3NDAsImp0aSI6ImI0NDE4ZTcyZDQ3ODQzMzA4ZjRjYzUxNjI2Y2JmYzFhIiwidXNlcl9pZCI6IjMifQ.crfCpcPo9N_V83hY1yrO27appYWm_9wx1K15wSSY4aw

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3ODQ4MDU0MCwiaWF0IjoxNzc3ODc1NzQwLCJqdGkiOiJkMmQ1YTZlZTYzMzY0ZDA0OTI1YzBkOGQ4YWM0MGJhMSIsInVzZXJfaWQiOiIzIn0.eycTcPn6mOIq8YFXT1tmZcJPKyh6vTLCbdikjENMQdc"
}

