# Generated by Django 6.0.2 on 2026-04-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('FUNDED', 'Funded'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled'), ('DISPUTED', 'Disputed'), ('SPLIT_PAY', 'Split Pay')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='contractevent',
            name='event_type',
            field=models.CharField(choices=[('contract_created', 'Contract Created'), ('contract_cancelled', 'Contract Cancelled'), ('contract_funded', 'Contract Funded'), ('contract_activated', 'Contract Activated'), ('work_submitted', 'Work Submitted'), ('work_rejected', 'Work Rejected'), ('work_approved', 'Work Approved'), ('escrow_released', 'Escrow Released'), ('escrow_refunded', 'Escrow Refunded'), ('escrow_split', 'Escrow Split'), ('dispute_opened', 'Dispute Opened'), ('dispute_resolved', 'Dispute Resolved'), ('dispute_closed', 'Dispute Closed')], max_length=50),
        ),
    ]
