# Generated by Django 6.0.2 on 2026-03-07 07:02

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
        ('jobs', '0002_rename_owner_job_client_job_budget_job_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='price',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='user',
            new_name='freelancer',
        ),
        migrations.AddField(
            model_name='bid',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdraw', 'Withdraw')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('job', 'freelancer')},
        ),
    ]
