# Generated by Django 6.0.2 on 2026-03-10 05:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_rename_price_bid_amount_rename_user_bid_freelancer_and_more'),
        ('jobs', '0003_jobevent_job_jobs_job_status_7d017a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['job', 'status'], name='bids_bid_job_id_a2a630_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['freelancer'], name='bids_bid_freelan_cbb8b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='bid',
            constraint=models.UniqueConstraint(fields=('job', 'freelancer'), name='unique_bid_per_job_per_freelancer'),
        ),
    ]
