# Generated by Django 6.0.2 on 2026-03-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_alter_bid_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdraw', 'Withdraw'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
