#### CONTRACTS

GET http://localhost:8000/api/contracts/list/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc1NDIwODczLCJpYXQiOjE3NzU0MjA1NzMsImp0aSI6ImVhZmQ4ODM2MzEzYTQ5Y2NhYzIzMzAzODZjYTIwNWM1IiwidXNlcl9pZCI6IjIifQ.tMocyvuISaTSJanSDF5BE49RIiqvp4flO02ZDn6CY50

###

GET http://localhost:8000/api/contracts/detail/1/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc1NDIwODczLCJpYXQiOjE3NzU0MjA1NzMsImp0aSI6ImVhZmQ4ODM2MzEzYTQ5Y2NhYzIzMzAzODZjYTIwNWM1IiwidXNlcl9pZCI6IjIifQ.tMocyvuISaTSJanSDF5BE49RIiqvp4flO02ZDn6CY50

###

GET http://local:8000/api/contracts/client_user/list/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc1NDIwODczLCJpYXQiOjE3NzU0MjA1NzMsImp0aSI6ImVhZmQ4ODM2MzEzYTQ5Y2NhYzIzMzAzODZjYTIwNWM1IiwidXNlcl9pZCI6IjIifQ.tMocyvuISaTSJanSDF5BE49RIiqvp4flO02ZDn6CY50

###

GET http://local:8000/api/contracts/freelancer_user/list/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc1NDIwODczLCJpYXQiOjE3NzU0MjA1NzMsImp0aSI6ImVhZmQ4ODM2MzEzYTQ5Y2NhYzIzMzAzODZjYTIwNWM1IiwidXNlcl9pZCI6IjIifQ.tMocyvuISaTSJanSDF5BE49RIiqvp4flO02ZDn6CY50
