# Generated by Django 6.0.2 on 2026-04-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_transaction_transaction_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference_type',
            field=models.CharField(choices=[('CONTRACT', 'contract'), ('DISPUTE', 'dispute')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_direction',
            field=models.CharField(choices=[('CREDIT', 'credit'), ('DEBIT', 'debit')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('escrow_funded', 'Escrow_funded'), ('escrow_released', 'Escrow_released'), ('refund', 'Refund'), ('platform_fee', 'Platform_fee')], max_length=50),
        ),
    ]
