# Generated by Django 6.0.2 on 2026-04-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_transaction_reference_id_transaction_reference_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference_type',
            field=models.CharField(choices=[('CONTRACT', 'contract'), ('DISPUTE', 'dispute')], max_length=50),
        ),
    ]
