# Generated by Django 6.0.2 on 2026-04-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_transaction_reference_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference_type',
            field=models.CharField(blank=True, choices=[('contract', 'Contract'), ('dispute', 'Dispute'), ('wallet_topup', 'Wallet_topup')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_direction',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('escrow_funded', 'Escrow_funded'), ('escrow_released', 'Escrow_released'), ('refund', 'Refund'), ('platform_fee', 'Platform_fee')], max_length=50),
        ),
    ]
