# Generated by Django 6.0.2 on 2026-04-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_direction',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=50, null=True),
        ),
    ]
