# Generated by Django 6.0.2 on 2026-04-21 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bids', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bid',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='jobs.job'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['job', 'status'], name='bids_bid_job_id_a2a630_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['freelancer'], name='bids_bid_freelan_cbb8b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='bid',
            constraint=models.UniqueConstraint(fields=('job', 'freelancer'), name='unique_bid_per_job_per_freelancer'),
        ),
    ]
