# Generated by Django 6.0.2 on 2026-03-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobevent_job_jobs_job_status_7d017a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobevent',
            name='event_type',
            field=models.CharField(choices=[('job_created', 'Job Created'), ('job_updated', 'Job Updated'), ('job_closed', 'Job Closed'), ('bid_placed', 'Bid Placed'), ('bid_accepted', 'Bid Accepted'), ('bid_rejected', 'Bid Rejected'), ('bid_withdrew', 'Bid Withdrew'), ('bid_updated', 'Bid Updated')], max_length=50),
        ),
    ]
