# Generated by Django 6.0.2 on 2026-03-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_jobevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobevent',
            name='event_type',
            field=models.CharField(choices=[('job_created', 'Job Created'), ('job_updated', 'Job Updated'), ('job_completed', 'Job Completed'), ('job_closed', 'Job Closed'), ('bid_placed', 'Bid Placed'), ('bid_accepted', 'Bid Accepted'), ('bid_rejected', 'Bid Rejected'), ('bid_withdrew', 'Bid Withdrew'), ('bid_updated', 'Bid Updated')], max_length=50),
        ),
    ]
